### ISSUE TITLE
大佬，我是1080的屏幕，睡眠唤醒不好使，应该从哪方面开始排查呢？

### ISSUE THREAD

**Issue by zomgit** [Hadymic/Y9000X-Hackintosh#1]
谢谢谢谢！

**Comment by zomgit** [comment]
大佬，我的睡眠唤醒不好使，应该cong哪方面开始排查呢？

**Comment by hadymic** [comment]
已修复，具体可查看[该Issue](https://github.com/WangRicky/Y9000X-HACKINTOSH/issues/19)
